apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: namespace
objects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: ${NAME}
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ${NAME}-sa
      namespace: ${NAME}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: ${NAME}-sa-role
      namespace: ${NAME}
    rules:
      - apiGroups: [ '*' ]
        resources: [ '*' ]
        verbs: [ '*' ]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}-sa-rolebinding
      namespace: ${NAME}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: ${NAME}-sa-role
    subjects:
      - namespace: ${NAME}
        kind: ServiceAccount
        name: ${NAME}-sa
parameters:
  - name: NAME
    value: mk-e2e-tests
