apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: namespace
objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ${NAME}-sa
      namespace: ${NAME}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}-sa-rolebinding
      namespace: ${NAME}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: edit
    subjects:
      - namespace: ${NAME}
        kind: ServiceAccount
        name: ${NAME}-sa
parameters:
  - name: NAME
    value: mk-e2e-tests
